### ISSUE TITLE
Issues with viewing user profiles

### ISSUE THREAD

**Issue by back-lacking** [PrivacyDevel/nitter#61]
So I have an issue with viewing the profiles of users using my personally hosted nitter instance. trying to visit the profiles of users will result in an error saying `user not found`. if i try to open it in a new tab, it will just be stuck on a blank screen forever 
looking at the logs of the nitter container dont seem to reveal much (old log text from months ago). when opening it in a new tab, the network flow would show an error like this 
![image](https://github.com/user-attachments/assets/e72a12f5-f1a6-44b6-af54-c44881febb68)

below is my compose for nitter:
```yaml
version: "3"
services:
  nitter:
    image: ghcr.io/privacydevel/nitter:master
    container_name: nitter
    volumes:
      - ./nitter.conf:/src/nitter.conf:Z,ro
      - ./guest_accounts.json:/src/guest_accounts.json:ro
    depends_on:
      - nitter-redis
    restart: unless-stopped
    networks:
      - proxy
      - nitter
    labels:
      - traefik.enable=true
      - traefik.http.routers.nitter.entrypoints=web
      - traefik.http.routers.nitter.rule=Host(`nitter.local.domain`)
      - traefik.http.middlewares.nitter-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.nitter.middlewares=nitter-https-redirect
      - traefik.http.routers.nitter-secure.entrypoints=websecure
      - traefik.http.routers.nitter-secure.rule=Host(`nitter.local.domain`)
      - traefik.http.routers.nitter-secure.tls=true
      - traefik.http.routers.nitter-secure.service=nitter
      - traefik.http.services.nitter.loadbalancer.server.port=8080
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:8080/Jack/status/20 || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    user: 998:998
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
  nitter-redis:
    image: redis:6-alpine
    container_name: nitter-redis
    hostname: nitter-redis
    ports:
      - 6379
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - nitter
    volumes:
      - nitter-redis:/data
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 5s
      retries: 2
    user: 999:1000
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
volumes:
  nitter-redis: null
networks:
  nitter: null
  proxy:
    external: true
```
